services:

  app:
    image: l4rm4nd/vouchervault
    restart: unless-stopped
    environment:
      - DOMAIN
      - SECURE_COOKIES=True
      - SESSION_COOKIE_AGE=43800
      - SESSION_EXPIRE_AT_BROWSER_CLOSE=False
      - EXPIRY_THRESHOLD_DAYS=90
      - EXPIRY_LAST_NOTIFICATION_DAYS=7
      - TZ=Europe/Berlin
      - SECRET_KEY
      - PORT=8000
      - REDIS_URL=redis://cache:6379/0
      - DB_ENGINE=postgres
      - POSTGRES_USER=vouchervault
      - POSTGRES_PASSWORD=vouchervault
      - POSTGRES_DB=vouchervault
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - app_data:/opt/app/database
    networks:
      app_database:
      proxy_apps:
      app_cache:

  cache:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      app_cache:

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vouchervault
      POSTGRES_USER: vouchervault
      POSTGRES_PASSWORD: vouchervault
    networks:
      app_database:
    labels:
      ofelia.restart: "true"
      ofelia.enabled: "true"
      ofelia.job-exec.vouchervaultdbbackup.schedule: "0 0 1 * * *"
      ofelia.job-exec.vouchervaultdbbackup.command: "sh -c 'pg_dumpall -U vouchervault -f /var/lib/postgresql/data/backup.sql'"

networks:
  app_database:
  app_cache:
  proxy_apps:
    name: proxy_apps
    external: true